/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsUserIdRouteImport } from './routes/students.$userId'
import { Route as SignupSplatRouteImport } from './routes/signup.$'
import { Route as OrganizationSettingsRouteImport } from './routes/organization.settings'
import { Route as OrganizationMembersRouteImport } from './routes/organization.members'
import { Route as OrganizationBoardsRouteImport } from './routes/organization.boards'
import { Route as LoginSplatRouteImport } from './routes/login.$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsUserIdRoute = StudentsUserIdRouteImport.update({
  id: '/students/$userId',
  path: '/students/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupSplatRoute = SignupSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignupRoute,
} as any)
const OrganizationSettingsRoute = OrganizationSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationMembersRoute = OrganizationMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationBoardsRoute = OrganizationBoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => OrganizationRoute,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/login': typeof LoginRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/signup': typeof SignupRouteWithChildren
  '/login/$': typeof LoginSplatRoute
  '/organization/boards': typeof OrganizationBoardsRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/signup/$': typeof SignupSplatRoute
  '/students/$userId': typeof StudentsUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/login': typeof LoginRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/signup': typeof SignupRouteWithChildren
  '/login/$': typeof LoginSplatRoute
  '/organization/boards': typeof OrganizationBoardsRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/signup/$': typeof SignupSplatRoute
  '/students/$userId': typeof StudentsUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/login': typeof LoginRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/signup': typeof SignupRouteWithChildren
  '/login/$': typeof LoginSplatRoute
  '/organization/boards': typeof OrganizationBoardsRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/signup/$': typeof SignupSplatRoute
  '/students/$userId': typeof StudentsUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/login'
    | '/organization'
    | '/signup'
    | '/login/$'
    | '/organization/boards'
    | '/organization/members'
    | '/organization/settings'
    | '/signup/$'
    | '/students/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/login'
    | '/organization'
    | '/signup'
    | '/login/$'
    | '/organization/boards'
    | '/organization/members'
    | '/organization/settings'
    | '/signup/$'
    | '/students/$userId'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/login'
    | '/organization'
    | '/signup'
    | '/login/$'
    | '/organization/boards'
    | '/organization/members'
    | '/organization/settings'
    | '/signup/$'
    | '/students/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  LoginRoute: typeof LoginRouteWithChildren
  OrganizationRoute: typeof OrganizationRouteWithChildren
  SignupRoute: typeof SignupRouteWithChildren
  StudentsUserIdRoute: typeof StudentsUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$userId': {
      id: '/students/$userId'
      path: '/students/$userId'
      fullPath: '/students/$userId'
      preLoaderRoute: typeof StudentsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/$': {
      id: '/signup/$'
      path: '/$'
      fullPath: '/signup/$'
      preLoaderRoute: typeof SignupSplatRouteImport
      parentRoute: typeof SignupRoute
    }
    '/organization/settings': {
      id: '/organization/settings'
      path: '/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof OrganizationSettingsRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/members': {
      id: '/organization/members'
      path: '/members'
      fullPath: '/organization/members'
      preLoaderRoute: typeof OrganizationMembersRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/boards': {
      id: '/organization/boards'
      path: '/boards'
      fullPath: '/organization/boards'
      preLoaderRoute: typeof OrganizationBoardsRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/login/$': {
      id: '/login/$'
      path: '/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof LoginRoute
    }
  }
}

interface LoginRouteChildren {
  LoginSplatRoute: typeof LoginSplatRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginSplatRoute: LoginSplatRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface OrganizationRouteChildren {
  OrganizationBoardsRoute: typeof OrganizationBoardsRoute
  OrganizationMembersRoute: typeof OrganizationMembersRoute
  OrganizationSettingsRoute: typeof OrganizationSettingsRoute
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationBoardsRoute: OrganizationBoardsRoute,
  OrganizationMembersRoute: OrganizationMembersRoute,
  OrganizationSettingsRoute: OrganizationSettingsRoute,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

interface SignupRouteChildren {
  SignupSplatRoute: typeof SignupSplatRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupSplatRoute: SignupSplatRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  LoginRoute: LoginRouteWithChildren,
  OrganizationRoute: OrganizationRouteWithChildren,
  SignupRoute: SignupRouteWithChildren,
  StudentsUserIdRoute: StudentsUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
